openapi: 3.0.0
info:
  title: SPARK AI Prompt Library API
  description: API for accessing 1,812+ professional AI prompts across 9 business departments
  version: 1.0.0
servers:
  - url: https://spark-copilot-api.azurewebsites.net/api
    description: Production API
paths:
  /prompts:
    get:
      operationId: getPrompts
      summary: Get AI prompts
      description: Retrieve AI prompts filtered by department, subcategory, or search term
      parameters:
        - name: department
          in: query
          description: Filter by department (Business, Marketing, Sales, SEO, Finance, Education, Writing, Productivity, Solopreneurs)
          required: false
          schema:
            type: string
            enum:
              - Business
              - Marketing
              - Sales
              - SEO
              - Finance
              - Education
              - Writing
              - Productivity
              - Solopreneurs
        - name: subcategory
          in: query
          description: Filter by subcategory (e.g., Business Communications, Content Strategy)
          required: false
          schema:
            type: string
        - name: search
          in: query
          description: Search term to filter prompts by title, description, or content
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: Maximum number of results to return
          required: false
          schema:
            type: integer
            default: 50
            maximum: 100
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                    description: Total number of prompts returned
                  prompts:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: Unique prompt identifier
                        title:
                          type: string
                          description: Prompt title
                        department:
                          type: string
                          description: Department category
                        subcategory:
                          type: string
                          description: Subcategory classification
                        description:
                          type: string
                          description: Brief prompt description
                        content:
                          type: string
                          description: Full prompt content
                        icon:
                          type: string
                          description: Department icon
                        word_count:
                          type: integer
                          description: Prompt word count
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  message:
                    type: string
